import 'package:cv_desing_website_flutter/domain/category.dart';
import 'package:cv_desing_website_flutter/domain/desing.dart';

class DesingData {
  static final desings = [
    Desing(
      id: 1,
      reference: 'CV10A',
      fileName: 'CV10A.jpg',
      category: Category.curriculum,
      price: 10,
    ),
    Desing(
      id: 2,
      reference: 'CV10B',
      fileName: 'CV10B.jpg',
      category: Category.curriculum,
      price: 10,
    ),
    Desing(
      id: 3,
      reference: 'CV10C',
      fileName: 'CV10C.jpg',
      category: Category.curriculum,
      price: 10,
    ),
    Desing(
      id: 4,
      reference: 'CV12A',
      fileName: 'CV12A.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 5,
      reference: 'CV12B',
      fileName: 'CV12B.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 6,
      reference: 'CV12C',
      fileName: 'CV12C.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 7,
      reference: 'CV12D',
      fileName: 'CV12D.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 8,
      reference: 'CV12E',
      fileName: 'CV12E.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 9,
      reference: 'CV12F',
      fileName: 'CV12F.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 10,
      reference: 'CV12G',
      fileName: 'CV12G.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 11,
      reference: 'CV12H',
      fileName: 'CV12H.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 12,
      reference: 'CV12J',
      fileName: 'CV12J.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 13,
      reference: 'CV12K',
      fileName: 'CV12K.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 14,
      reference: 'CV12L',
      fileName: 'CV12L.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 15,
      reference: 'CV12M',
      fileName: 'CV12M.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 16,
      reference: 'CV12N',
      fileName: 'CV12N.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 17,
      reference: 'CV12O',
      fileName: 'CV12O.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 18,
      reference: 'CV12P',
      fileName: 'CV12P.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 19,
      reference: 'CV12Q',
      fileName: 'CV12Q.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 20,
      reference: 'CV12R',
      fileName: 'CV12R.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 21,
      reference: 'CV12S',
      fileName: 'CV12S.jpg',
      category: Category.curriculum,
      price: 12,
    ),
    Desing(
      id: 22,
      reference: 'F5A',
      fileName: 'F5A.jpg',
      category: Category.flyer,
      price: 5,
    ),
    Desing(
      id: 23,
      reference: 'F5B',
      fileName: 'F5B.jpg',
      category: Category.flyer,
      price: 5,
    ),
    Desing(
      id: 24,
      reference: 'F5C',
      fileName: 'F5C.jpg',
      category: Category.flyer,
      price: 5,
    ),
    Desing(
      id: 25,
      reference: 'T10A',
      fileName: 'T10A.jpg',
      category: Category.businessCard,
      price: 10,
    ),
    Desing(
      id: 26,
      reference: 'T10B',
      fileName: 'T10B.jpg',
      category: Category.businessCard,
      price: 10,
    ),
    Desing(
      id: 27,
      reference: 'T10C',
      fileName: 'T10C.jpg',
      category: Category.businessCard,
      price: 10,
    ),
    Desing(
      id: 28,
      reference: 'T10D',
      fileName: 'T10D.jpg',
      category: Category.businessCard,
      price: 10,
    ),
    Desing(
      id: 29,
      reference: 'T10E',
      fileName: 'T10E.jpg',
      category: Category.businessCard,
      price: 10,
    ),
    Desing(
      id: 30,
      reference: 'T10F',
      fileName: 'T10F.jpg',
      category: Category.businessCard,
      price: 10,
    ),
    Desing(
      id: 31,
      reference: 'T10G',
      fileName: 'T10G.jpg',
      category: Category.businessCard,
      price: 10,
    ),
    Desing(
      id: 32,
      reference: 'T10H',
      fileName: 'T10H.jpg',
      category: Category.businessCard,
      price: 10,
    ),
  ];
}
