include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false  
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true    
 
analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore