name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter pub get
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /
          customArgs: --dart-define="FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" --dart-define="FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" --dart-define="FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" --dart-define="FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" --dart-define="FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" --dart-define="FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" --dart-define="FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" 

